---
- name: Make sure pihole is set up first
  hosts: automation
  become: yes
  gather_facts: True
  tags: automation
  pre_tasks:
  - name: get secrets
    include_vars: secrets.yaml
 
  roles:
    - pihole

- name: Set up common tasks on all servers
  hosts: all
  become: yes
  gather_facts: True
  
  roles: 
    - common

- name: Configure proxy
  hosts: proxy
  become: yes
  tags: proxy

  roles:
    - proxy


- name: Set up home media
  hosts: automation
  become: yes
  gather_facts: True
  tags: automation
 
  roles:
    - sabnzbd
    - plex
    - sonarr
    - radarr

- name: Set up home automation
  hosts: automation
  become: yes
  gather_facts: True

  tags:
  - automation
  - hass
  - hass_config

  roles:
    - home-assistant
