---
# tasks file for proxy
- name: Add firewall init script for network
  template:
    src: iptables.j2
    dest: /etc/network/if-up.d/iptables
    mode: 0750

- name: Make directory for iptables config
  file:
    path: "{{ iptables_config_base }}"
    state: directory

- name: Add iptables rule for 443 input
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 443
    jump: ACCEPT
    ip_version: ipv4
    match: state
    ctstate: 
    - NEW
    - ESTABLISHED
  notify: save iptables ipv4

- name: Add iptables rule for 443 output
  iptables:
    chain: OUTPUT
    protocol: tcp
    source_port: 443
    jump: ACCEPT
    ip_version: ipv4
    match: state
    ctstate: 
    - ESTABLISHED
  notify: save iptables ipv4

- name: Add key for nginx repo
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present
  
# - name: install nginx
#   apt:
#     name: nginx
#     state: present
#     update_cache: yes

# - name: Add stretch backports repo
#   apt_repository:
#     repo: deb http://ftp.debian.org/debian stretch-backports main
#     validate_certs: no
#     state: present
  
# - name: install certbot
#   apt:
#     name: python-certbot-nginx
#     default_release: stretch-backports
#     state: present
#     update_cache: yes
#     allow_unauthenticated: yes
