homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 30.105399
  longitude: -81.565513
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 5
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: http://lester001:8123
  api_password: !secret http_password
  # api_password: test

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  enable:
   - homekit

tplink:
  discovery: false
  switch:
  - host: 10.0.0.23
  - host: 10.0.0.24
  - host: 10.0.0.25


homekit:
  auto_start: false
  filter:
    # include_domains:
    #   # - alarm_control_panel
    #   # - light
    include_entities:
      - switch.outdoor_switch_00550934
    exclude_domains:
      - sensor
      - automation
      - binary_sensor
      - group
      - scene
    exclude_entities:
      # HUE Rooms
      - light.family_room
      - light.living_room
      - light.master_bedroom
      # Rachio 
      - binary_sensor.rachio_online
      - switch.rachio_in_standby_mode
      - switch.back_shrubs_east
      - switch.back_yard
      - switch.front_shrubs_west
      - switch.front_yard

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
#  - platform: yr
  - platform: darksky
    api_key: 6772f2d7247f6ea4fdbcdf51341d44f0
    monitored_conditions:
      - summary
      - temperature
      - uv_index
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

# iOS 
# ios:

# Weather
weather:
  - platform: darksky
    api_key: 6772f2d7247f6ea4fdbcdf51341d44f0

# Switches for presense tracking
input_boolean:
  tom_presence:
    name: tom
    icon: mdi:account
  melissa_presence:
    name: melissa
    icon: mdi:account
  rachel_presence:
    name: rachel
    icon: mdi:account

binary_sensor:
  - platform: template
    sensors:
      presence_tom:
        friendly_name: "Tom Presence"
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.tom_presence', 'on') }}  
  - platform: template
    sensors:
      presence_melissa:
        friendly_name: "Melissa Presence"
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.melissa_presence', 'on') }}  
  - platform: template
    sensors:
      presence_rachel:
        friendly_name: "Rachel Presence"
        device_class: presence
        value_template: >-
          {{ is_state('input_boolean.rachel_presence', 'on') }}  
  # Ping Google
  - platform: ping
    host: google.com
    scan_interval: 60
    name: internet

# Sonos
sonos:
  media_player:
    hosts:
      - 10.0.0.15
      - 10.0.0.18

# Rachio
rachio:
  api_key: cd851af6-4deb-4750-9cdd-d44faed514e6

group: !include groups.yaml
scene: !include scenes.yaml
automation: !include automations.yaml
script: !include scripts.yaml
cloud: !include cloud.yaml
