---
# handlers file for pihole
- name: restart docker
  service:
    name: docker
    state: restarted

- name: save iptables ipv4
  shell: /sbin/iptables-save > {{ iptables_config }}

- name: save iptables ipv6
  shell: /sbin/ip6tables-save > {{ ip6tables_config }}
