---
# tasks file for common

- name: Define hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Download pip installer
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py

- name: Install pip
  command: python /tmp/get-pip.py

- name: Update pip
  pip:
    name: pip
    state: latest

- name: Make sure vim is present
  apt:
    name: vim
    state: present
  